# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: NodePort
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 3000
  nodePort: 30080

image:
  repository: demoappregistry.azurecr.io/demoapp
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # # Overrides the image tag whose default is the chart appVersion.
  # tag: "1.7.9"

# imagePullSecrets:
#   - name: registry-creds

# kubectl create secret generic my-secret --from-literal=key1=supersecret --from-literal=key2=topsecret

replicaCount: 2

# volumes:
#   - name: nginx-config
#     configMap:
#       name: nginx-app-config

# # Additional volumeMounts on the output Deployment definition.
# volumeMounts:
#   - name: nginx-config
#     mountPath: "/etc/nginx/conf.d/default.conf"
#     subPath: default.conf